sidebar:
  logo:
    title: '[<img no-lazy height="32px" src="http://rebp38war.bkt.clouddn.com/img/s.jpg"/>](/)'
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[笔记](/notes/)'
    more: '[更多](/more/)'
  article:
    auto_cover: true